import type { Integration, SyncHistoryEntry, IntegrationHealthKPI } from "./types";

// ─── Integrations by Category ─────────────────────────────────────────────────

export const integrations: Integration[] = [
  // CRM
  {
    id: "gohighlevel",
    name: "GoHighLevel",
    description: "CRM, pipeline management, marketing automation and conversations.",
    category: "CRM",
    logoInitials: "GHL",
    logoColor: "#E31B23",
    status: "connected",
    connectedAccount: "crediedge@gohighlevel.com",
    lastSync: "2 min ago",
    version: "v2.1",
    health: "healthy",
    permissions: ["Read contacts", "Write contacts", "Read conversations", "Send messages", "Manage pipelines"],
    syncFrequency: "Real-time",
    featured: true,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Inbound CRM with contact management and marketing tools.",
    category: "CRM",
    logoInitials: "HS",
    logoColor: "#FF7A59",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read contacts", "Write contacts", "Read deals", "Manage workflows"],
    featured: false,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Enterprise CRM platform for sales and customer management.",
    category: "CRM",
    logoInitials: "SF",
    logoColor: "#00A1E0",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read contacts", "Write contacts", "Manage opportunities", "Custom fields"],
    featured: false,
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Sales-focused CRM with visual pipeline management.",
    category: "CRM",
    logoInitials: "PD",
    logoColor: "#1A1A1A",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read contacts", "Write contacts", "Read pipelines"],
    featured: false,
  },
  {
    id: "zoho",
    name: "Zoho CRM",
    description: "All-in-one CRM with sales, marketing and support tools.",
    category: "CRM",
    logoInitials: "ZC",
    logoColor: "#E42527",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read contacts", "Write contacts", "Manage modules"],
    featured: false,
  },

  // Communication
  {
    id: "gmail",
    name: "Gmail",
    description: "Google email with conversation threading and labels.",
    category: "Communication",
    logoInitials: "GM",
    logoColor: "#EA4335",
    status: "connected",
    connectedAccount: "dom@crediedge.co.uk",
    lastSync: "5 min ago",
    version: "v1",
    health: "healthy",
    permissions: ["Read emails", "Send emails", "Manage labels", "Read contacts"],
    syncFrequency: "Every 5 minutes",
    featured: true,
  },
  {
    id: "outlook",
    name: "Outlook",
    description: "Microsoft email, calendar and contacts platform.",
    category: "Communication",
    logoInitials: "OL",
    logoColor: "#0078D4",
    status: "warning",
    connectedAccount: "dom@crediedge.co.uk",
    lastSync: "45 min ago",
    version: "v2",
    health: "degraded",
    permissions: ["Read emails", "Send emails", "Read calendar"],
    syncFrequency: "Every 15 minutes",
    featured: false,
  },
  {
    id: "whatsapp",
    name: "WhatsApp Business",
    description: "WhatsApp Business API for customer messaging.",
    category: "Communication",
    logoInitials: "WA",
    logoColor: "#25D366",
    status: "connected",
    connectedAccount: "+44 7700 900000",
    lastSync: "1 min ago",
    version: "Cloud API",
    health: "healthy",
    permissions: ["Send messages", "Receive messages", "Read contacts"],
    syncFrequency: "Real-time",
    featured: true,
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, voice calls and programmable messaging API.",
    category: "Communication",
    logoInitials: "TW",
    logoColor: "#F22F46",
    status: "disconnected",
    health: "unknown",
    permissions: ["Send SMS", "Receive SMS", "Make calls", "Receive calls"],
    featured: false,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team messaging with channel-based collaboration.",
    category: "Communication",
    logoInitials: "#",
    logoColor: "#4A154B",
    status: "connected",
    connectedAccount: "CrediEdge Workspace",
    lastSync: "8 min ago",
    health: "healthy",
    permissions: ["Post messages", "Read channels", "Manage notifications"],
    syncFrequency: "Real-time alerts",
    featured: false,
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    description: "Microsoft collaboration with meetings and messaging.",
    category: "Communication",
    logoInitials: "MT",
    logoColor: "#464EB8",
    status: "disconnected",
    health: "unknown",
    permissions: ["Post messages", "Create meetings"],
    featured: false,
  },

  // Calendar
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Appointment scheduling and booking synchronisation.",
    category: "Calendar",
    logoInitials: "GC",
    logoColor: "#4285F4",
    status: "connected",
    connectedAccount: "dom@crediedge.co.uk",
    lastSync: "3 min ago",
    health: "healthy",
    permissions: ["Read events", "Create events", "Delete events", "Manage calendars"],
    syncFrequency: "Real-time",
    featured: true,
  },
  {
    id: "ms-calendar",
    name: "Microsoft Calendar",
    description: "Outlook calendar with meeting management.",
    category: "Calendar",
    logoInitials: "MC",
    logoColor: "#0078D4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read events", "Create events"],
    featured: false,
  },
  {
    id: "apple-calendar",
    name: "Apple Calendar",
    description: "iCloud calendar sync for Apple device users.",
    category: "Calendar",
    logoInitials: "AC",
    logoColor: "#1A1A1A",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read events", "Create events"],
    featured: false,
  },

  // Finance
  {
    id: "stripe",
    name: "Stripe",
    description: "Payment processing, subscriptions and billing.",
    category: "Finance",
    logoInitials: "S",
    logoColor: "#635BFF",
    status: "connected",
    connectedAccount: "crediedge@stripe.com",
    lastSync: "3 min ago",
    version: "v2024",
    health: "healthy",
    permissions: ["Read payments", "Create charges", "Manage subscriptions", "View payouts"],
    syncFrequency: "Real-time",
    featured: true,
  },
  {
    id: "xero",
    name: "Xero",
    description: "Invoicing, payroll, expenses and financial reporting.",
    category: "Finance",
    logoInitials: "X",
    logoColor: "#13B5EA",
    status: "connected",
    connectedAccount: "crediedge@xero.com",
    lastSync: "1 hr ago",
    version: "v2.0",
    health: "healthy",
    permissions: ["Read invoices", "Create invoices", "Read contacts", "Read accounts"],
    syncFrequency: "Hourly",
    featured: true,
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Small business accounting and tax management.",
    category: "Finance",
    logoInitials: "QB",
    logoColor: "#2CA01C",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read invoices", "Create invoices", "Read reports"],
    featured: false,
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Online payments, invoicing and merchant services.",
    category: "Finance",
    logoInitials: "PP",
    logoColor: "#003087",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read transactions", "Send invoices"],
    featured: false,
  },

  // Website
  {
    id: "wordpress",
    name: "WordPress",
    description: "CMS integration for content and form management.",
    category: "Website",
    logoInitials: "WP",
    logoColor: "#21759B",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read pages", "Read forms", "Read analytics"],
    featured: false,
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "No-code website builder with CMS capabilities.",
    category: "Website",
    logoInitials: "WF",
    logoColor: "#4353FF",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read pages", "Read CMS", "Read forms"],
    featured: false,
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "E-commerce platform for online retail management.",
    category: "Website",
    logoInitials: "SH",
    logoColor: "#5C6AC4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read orders", "Read products", "Read customers"],
    featured: false,
  },
  {
    id: "ga",
    name: "Google Analytics",
    description: "Website traffic, behaviour and conversion analytics.",
    category: "Website",
    logoInitials: "GA",
    logoColor: "#E37400",
    status: "connected",
    connectedAccount: "UA-123456789",
    lastSync: "1 hour ago",
    health: "healthy",
    permissions: ["Read reports", "Read real-time data"],
    syncFrequency: "Hourly",
    featured: true,
  },
  {
    id: "gsc",
    name: "Search Console",
    description: "Google Search Console for SEO and ranking insights.",
    category: "Website",
    logoInitials: "SC",
    logoColor: "#4CAF50",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read search analytics", "Read crawl data"],
    featured: false,
  },
  {
    id: "gtm",
    name: "Google Tag Manager",
    description: "Tag management and tracking code deployment.",
    category: "Website",
    logoInitials: "GTM",
    logoColor: "#4285F4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read tags", "Publish containers"],
    featured: false,
  },
  {
    id: "clarity",
    name: "Microsoft Clarity",
    description: "Heatmaps, session recordings and UX analytics.",
    category: "Website",
    logoInitials: "MC",
    logoColor: "#0078D4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read heatmaps", "Read sessions", "Read recordings"],
    featured: false,
  },

  // Social Media
  {
    id: "facebook",
    name: "Facebook",
    description: "Facebook Page, Ads and Messenger integration.",
    category: "Social Media",
    logoInitials: "FB",
    logoColor: "#1877F2",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read page", "Post content", "Read messages", "Read ads"],
    featured: false,
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "Instagram Business for posts, stories and DMs.",
    category: "Social Media",
    logoInitials: "IG",
    logoColor: "#E1306C",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read profile", "Post content", "Read DMs"],
    featured: false,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "LinkedIn Company Page and professional networking.",
    category: "Social Media",
    logoInitials: "LI",
    logoColor: "#0A66C2",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read profile", "Post content"],
    featured: false,
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "TikTok Business Centre for content and analytics.",
    category: "Social Media",
    logoInitials: "TT",
    logoColor: "#1A1A1A",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read profile", "Post content", "Read analytics"],
    featured: false,
  },
  {
    id: "x",
    name: "X (Twitter)",
    description: "X Business for posts, replies and analytics.",
    category: "Social Media",
    logoInitials: "X",
    logoColor: "#1A1A1A",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read profile", "Post content", "Read mentions"],
    featured: false,
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "YouTube channel management and video analytics.",
    category: "Social Media",
    logoInitials: "YT",
    logoColor: "#FF0000",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read channel", "Post videos", "Read analytics"],
    featured: false,
  },

  // Review Platforms
  {
    id: "google-reviews",
    name: "Google Reviews",
    description: "Google Business Profile reviews and response management.",
    category: "Review Platforms",
    logoInitials: "GR",
    logoColor: "#4285F4",
    status: "connected",
    connectedAccount: "CrediEdge Automotive",
    lastSync: "12 min ago",
    health: "healthy",
    permissions: ["Read reviews", "Post replies", "Read profile"],
    syncFrequency: "Every 15 minutes",
    featured: true,
  },
  {
    id: "trustpilot",
    name: "Trustpilot",
    description: "Trustpilot reviews, invitations and reply management.",
    category: "Review Platforms",
    logoInitials: "TP",
    logoColor: "#00B67A",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read reviews", "Send invitations", "Post replies"],
    featured: false,
  },
  {
    id: "facebook-reviews",
    name: "Facebook Reviews",
    description: "Facebook Page recommendations and review responses.",
    category: "Review Platforms",
    logoInitials: "FR",
    logoColor: "#1877F2",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read reviews", "Post replies"],
    featured: false,
  },
  {
    id: "yelp",
    name: "Yelp",
    description: "Yelp Business reviews and local search presence.",
    category: "Review Platforms",
    logoInitials: "YP",
    logoColor: "#D32323",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read reviews", "Post replies", "Read profile"],
    featured: false,
  },
  {
    id: "tripadvisor",
    name: "TripAdvisor",
    description: "TripAdvisor reviews and hospitality management.",
    category: "Review Platforms",
    logoInitials: "TA",
    logoColor: "#34E0A1",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read reviews", "Post replies"],
    featured: false,
  },

  // AI
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4 and advanced reasoning models for AI features.",
    category: "AI",
    logoInitials: "AI",
    logoColor: "#1A1A1A",
    status: "connected",
    connectedAccount: "org-crediedge",
    lastSync: "Active",
    health: "healthy",
    permissions: ["Chat completions", "Embeddings", "Function calling"],
    syncFrequency: "On demand",
    featured: true,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude AI models for analysis and generation.",
    category: "AI",
    logoInitials: "AN",
    logoColor: "#D97706",
    status: "disconnected",
    health: "unknown",
    permissions: ["Chat completions", "Document analysis"],
    featured: false,
  },
  {
    id: "gemini",
    name: "Google Gemini",
    description: "Google's multimodal AI for text, image and data.",
    category: "AI",
    logoInitials: "GG",
    logoColor: "#4285F4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Chat completions", "Multimodal analysis"],
    featured: false,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "Real-time AI search and market intelligence.",
    category: "AI",
    logoInitials: "PX",
    logoColor: "#20B2AA",
    status: "disconnected",
    health: "unknown",
    permissions: ["Search queries", "Real-time data"],
    featured: false,
  },

  // Automation
  {
    id: "zapier",
    name: "Zapier",
    description: "No-code automation between thousands of apps.",
    category: "Automation",
    logoInitials: "ZP",
    logoColor: "#FF4A00",
    status: "disconnected",
    health: "unknown",
    permissions: ["Trigger zaps", "Receive webhooks"],
    featured: false,
  },
  {
    id: "make",
    name: "Make.com",
    description: "Visual automation builder with advanced logic.",
    category: "Automation",
    logoInitials: "MK",
    logoColor: "#6D00CC",
    status: "disconnected",
    health: "unknown",
    permissions: ["Trigger scenarios", "Receive webhooks"],
    featured: false,
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Open-source workflow automation with self-hosting.",
    category: "Automation",
    logoInitials: "n8",
    logoColor: "#EA4B71",
    status: "disconnected",
    health: "unknown",
    permissions: ["Trigger workflows", "Receive webhooks"],
    featured: false,
  },

  // Storage
  {
    id: "gdrive",
    name: "Google Drive",
    description: "Cloud storage for documents, files and backups.",
    category: "Storage",
    logoInitials: "GD",
    logoColor: "#4285F4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read files", "Write files", "Create folders"],
    featured: false,
  },
  {
    id: "dropbox",
    name: "Dropbox",
    description: "File hosting, sharing and collaboration platform.",
    category: "Storage",
    logoInitials: "DB",
    logoColor: "#0061FF",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read files", "Write files"],
    featured: false,
  },
  {
    id: "onedrive",
    name: "OneDrive",
    description: "Microsoft cloud storage with Office 365 integration.",
    category: "Storage",
    logoInitials: "OD",
    logoColor: "#0078D4",
    status: "disconnected",
    health: "unknown",
    permissions: ["Read files", "Write files"],
    featured: false,
  },

  // Developer
  {
    id: "rest-api",
    name: "REST API",
    description: "Custom REST API integration for bespoke connections.",
    category: "Developer",
    logoInitials: "API",
    logoColor: "#1A1A1A",
    status: "connected",
    connectedAccount: "CrediEdgeOS API v1",
    lastSync: "Active",
    health: "healthy",
    permissions: ["Full API access", "Read data", "Write data", "Manage webhooks"],
    syncFrequency: "On demand",
    featured: false,
  },
  {
    id: "webhooks",
    name: "Webhooks",
    description: "Receive real-time event notifications from external services.",
    category: "Developer",
    logoInitials: "WH",
    logoColor: "#7C3AED",
    status: "connected",
    connectedAccount: "3 active endpoints",
    lastSync: "Real-time",
    health: "healthy",
    permissions: ["Receive webhooks", "Process events"],
    syncFrequency: "Real-time",
    featured: false,
  },
  {
    id: "api-keys",
    name: "API Keys",
    description: "Generate and manage API keys for partner integrations.",
    category: "Developer",
    logoInitials: "KEY",
    logoColor: "#D97706",
    status: "connected",
    connectedAccount: "4 active keys",
    lastSync: "—",
    health: "healthy",
    permissions: ["Generate keys", "Revoke keys", "View usage"],
    featured: false,
  },
];

// ─── Sync History ─────────────────────────────────────────────────────────────

export const syncHistory: SyncHistoryEntry[] = [
  { id: "s1", platform: "GoHighLevel", time: "09:42", status: "success", duration: "1.2s", recordsUpdated: 14, errors: 0, warnings: 0 },
  { id: "s2", platform: "Google Reviews", time: "09:30", status: "success", duration: "0.8s", recordsUpdated: 3, errors: 0, warnings: 0 },
  { id: "s3", platform: "Stripe", time: "09:27", status: "success", duration: "0.4s", recordsUpdated: 6, errors: 0, warnings: 0 },
  { id: "s4", platform: "Xero", time: "09:00", status: "success", duration: "2.1s", recordsUpdated: 8, errors: 0, warnings: 1 },
  { id: "s5", platform: "Outlook", time: "08:45", status: "warning", duration: "5.8s", recordsUpdated: 0, errors: 0, warnings: 3 },
  { id: "s6", platform: "Gmail", time: "08:40", status: "success", duration: "1.0s", recordsUpdated: 22, errors: 0, warnings: 0 },
  { id: "s7", platform: "Google Analytics", time: "08:00", status: "success", duration: "1.6s", recordsUpdated: 1, errors: 0, warnings: 0 },
  { id: "s8", platform: "WhatsApp Business", time: "07:55", status: "success", duration: "0.3s", recordsUpdated: 9, errors: 0, warnings: 0 },
];

// ─── Health KPIs ──────────────────────────────────────────────────────────────

export const healthKPIs: IntegrationHealthKPI[] = [
  { label: "Connected Services", value: 9, sublabel: "Active integrations", status: "ok" },
  { label: "Failed Connections", value: 1, sublabel: "Requires attention", status: "warning" },
  { label: "Pending Syncs", value: 0, sublabel: "Queue is clear", status: "ok" },
  { label: "Last Global Sync", value: "2 min ago", sublabel: "All services polled", status: "ok" },
  { label: "System Status", value: "Operational", sublabel: "All systems normal", status: "ok" },
  { label: "API Calls Today", value: "1,847", sublabel: "Within rate limits", status: "ok" },
];

export const INTEGRATION_CATEGORIES = [
  "All",
  "CRM",
  "Communication",
  "Calendar",
  "Finance",
  "Website",
  "Social Media",
  "Review Platforms",
  "AI",
  "Automation",
  "Storage",
  "Developer",
] as const;
