/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/calendar': typeof CalendarRoute
  '/communications': typeof CommunicationsRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/relationships': typeof RelationshipsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/website': typeof WebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/calendar': typeof CalendarRoute
  '/communications': typeof CommunicationsRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/relationships': typeof RelationshipsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/website': typeof WebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/calendar': typeof CalendarRoute
  '/communications': typeof CommunicationsRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/relationships': typeof RelationshipsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/website': typeof WebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/calendar'
    | '/communications'
    | '/goals'
    | '/health'
    | '/insights'
    | '/integrations'
    | '/intelligence'
    | '/relationships'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/calendar'
    | '/communications'
    | '/goals'
    | '/health'
    | '/insights'
    | '/integrations'
    | '/intelligence'
    | '/relationships'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/website'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/calendar'
    | '/communications'
    | '/goals'
    | '/health'
    | '/insights'
    | '/integrations'
    | '/intelligence'
    | '/relationships'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  CalendarRoute: typeof CalendarRoute
  CommunicationsRoute: typeof CommunicationsRoute
  GoalsRoute: typeof GoalsRoute
  HealthRoute: typeof HealthRoute
  InsightsRoute: typeof InsightsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  RelationshipsRoute: typeof RelationshipsRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WebsiteRoute: typeof WebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  CalendarRoute: CalendarRoute,
  CommunicationsRoute: CommunicationsRoute,
  GoalsRoute: GoalsRoute,
  HealthRoute: HealthRoute,
  InsightsRoute: InsightsRoute,
  IntegrationsRoute: IntegrationsRoute,
  IntelligenceRoute: IntelligenceRoute,
  RelationshipsRoute: RelationshipsRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WebsiteRoute: WebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
