-- ── CAMPAIGN & MISSION FIELD EXTENSIONS ────────────────────────────────

ALTER TABLE public.campaigns
    ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS priority VARCHAR(50) DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS actual_result NUMERIC(12, 2) DEFAULT 0;

ALTER TABLE public.missions
    ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS priority VARCHAR(50) DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS target_date TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS actual_result NUMERIC(12, 2) DEFAULT 0;
